repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: end-of-file-fixer
      name: End‑of‑file fixer (non‑Python)
      description: Ensures every *non‑Python* file is empty or ends with a single newline
      exclude: ^.*\.(json|pyi?|py)$

    - id: trailing-whitespace
      name: Trailing‑whitespace (non‑Python)
      description: Trims trailing whitespace in non‑Python text files
      exclude: ^.*\.(pyi?|py)$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
    - id: ruff
      name: Ruff (lint + autofix)
      description: Fast Python linter (Flake8, isort, quotes, etc.) with --fix enabled
      args: [--fix]

- repo: local
  hooks:
  - id: eslint-frontend
    name: ESLint (frontend)
    description: Run ESLint on TS/JS inside src/st_copy/frontend
    language: node
    entry: >
      npx eslint --fix
      --config src/st_copy/frontend/eslint.config.js
      --ext .js,.jsx,.ts,.tsx,.html
      src/st_copy/frontend
    require_serial: true
    pass_filenames: false

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.2
  hooks:
    - id: uv-lock
      name: Make sure uv.lock file is up to date
