"""Pure-Python unit tests for the ``st_copy`` wrapper.

They do *not* require a Streamlit runtime or browser. The Streamlit Components
v2 mounting command is replaced by a recorder so the public ``copy_button``
contract (argument forwarding, defaults, UUID-4 key autogeneration, the
``width='content'`` inline mount that fixes issue #27, and the tri-state return
value) can be asserted in isolation.
"""

import importlib
import uuid
from typing import Any

import pytest

import st_copy


class _RenderRecorder:
    """Capture the kwargs passed to the v2 mounting command; return a fixed result."""

    def __init__(self, result: Any = None) -> None:
        self.calls: list[dict[str, Any]] = []
        self.result = result

    def __call__(self, **kwargs: Any) -> Any:
        self.calls.append(kwargs)
        return self.result


@pytest.fixture
def st_copy_module() -> Any:
    """Reload ``st_copy`` so the cached mounting command is reset per test."""
    importlib.reload(st_copy)
    return st_copy


def _install_recorder(module: Any, result: Any = None) -> _RenderRecorder:
    """Replace the cached mounting command with a recorder and return it."""
    recorder = _RenderRecorder(result)
    module._component = recorder
    return recorder


@pytest.mark.parametrize(
    'call_kwargs',
    [
        # 1) no optional arguments - rely on defaults
        {},
        # 2) a subset of optional arguments
        {'tooltip': 'Copy this', 'key': 'foo'},
        # 3) *all* public arguments overridden
        {
            'icon': 'st',
            'tooltip': 'Special tip',
            'copied_label': 'Done!',
            'key': 'bar',
        },
    ],
)
def test_forwards_all_arguments(st_copy_module, call_kwargs):
    """``copy_button`` must forward every parameter to the component ``data`` payload."""
    recorder = _install_recorder(st_copy_module)

    st_copy_module.copy_button('hello', **call_kwargs)

    assert recorder.calls, 'component was never mounted'
    mounted = recorder.calls[0]
    data = mounted['data']

    # immutable parameter
    assert data['text'] == 'hello'

    # defaults applied unless overridden
    assert data['icon'] == call_kwargs.get('icon', 'material_symbols')
    assert data['tooltip'] == call_kwargs.get('tooltip', 'Copy')
    assert data['copied_label'] == call_kwargs.get('copied_label', 'Copied!')

    # explicit key is forwarded unchanged
    if 'key' in call_kwargs:
        assert mounted['key'] == call_kwargs['key']

    # a copied-trigger callback is always registered so the result exposes it
    assert callable(mounted['on_copied_change'])


def test_mounts_inline_for_horizontal_layout(st_copy_module):
    """The component must be mounted with ``width='content'`` (the issue #27 fix)."""
    recorder = _install_recorder(st_copy_module)
    st_copy_module.copy_button('hi')
    assert recorder.calls[0]['width'] == 'content'


@pytest.mark.parametrize('icon_val', ['material_symbols', 'st'])
def test_icon_forwarded(st_copy_module, icon_val):
    """The ``icon`` parameter must pass through unchanged."""
    recorder = _install_recorder(st_copy_module)
    st_copy_module.copy_button('hi', icon=icon_val)
    assert recorder.calls[0]['data']['icon'] == icon_val


def test_copied_label_default_and_custom(st_copy_module):
    """Check default and custom ``copied_label`` handling."""
    recorder = _install_recorder(st_copy_module)

    st_copy_module.copy_button('hi')
    assert recorder.calls[0]['data']['copied_label'] == 'Copied!'

    st_copy_module.copy_button('hi', copied_label='✅ Copied')
    assert recorder.calls[1]['data']['copied_label'] == '✅ Copied'


def test_key_autogenerated_uuid4(st_copy_module):
    """If ``key`` is omitted, the wrapper should generate a valid UUID-4 string."""
    recorder = _install_recorder(st_copy_module)
    st_copy_module.copy_button('hi')  # omit ``key``

    auto_key = recorder.calls[0]['key']
    # Will raise ValueError if not a valid UUID-4
    uuid_obj = uuid.UUID(auto_key, version=4)
    assert str(uuid_obj) == auto_key


def test_returns_true_when_copied(st_copy_module):
    """``copy_button`` returns ``True`` when the component reports a successful copy."""
    _install_recorder(st_copy_module, result={'copied': True})
    assert st_copy_module.copy_button('hi') is True


def test_returns_false_when_copy_failed(st_copy_module):
    """``copy_button`` returns ``False`` when the component reports a failed copy."""
    _install_recorder(st_copy_module, result={'copied': False})
    assert st_copy_module.copy_button('hi') is False


def test_returns_none_before_interaction(st_copy_module):
    """``copy_button`` returns ``None`` before the button has been clicked."""
    _install_recorder(st_copy_module, result={})
    assert st_copy_module.copy_button('hi') is None
